services:
  database:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: some

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    links:
      - database:db
