services:
  db:
    container_name: "postgres"
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: test # Optional, can be customized
      POSTGRES_DB: mydb # Optional, specify database name
    ports:
      - "5434:5432"
      # (HOST:CONTAINER)
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - app_network # Ensure db is accessible by the web and accounts containers
  web:
    build: ./NCKU/
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
      # (HOST:CONTAINER)
    volumes:
      - .:/app # Mount the current directory to the /app directory inside the container
    depends_on:
      - db
    networks:
      - app_network
  accounts:
    build: ./accounts/
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    restart: always
    ports:
      - "8080:8080"
      # (HOST:CONTAINER)
    volumes:
      - .:/app # Mount the current directory to the /app directory inside the container
    depends_on:
      - db
    networks:
      - app_network
volumes:
  pgdata: # Persistent volume for PostgreSQL data

networks:
  app_network: # Custom network for communication between containers
    driver: bridge
